# Налаштування для Docker-мережі
spring.datasource.url=jdbc:postgresql://db:5432/restaurant_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate автоматично створить таблиці
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Показувати SQL запити в консолі (корисно для перевірки)
spring.jpa.show-sql=true
